[package]
name = "prometheus"
version = "0.1.0"
edition = "2021"

[dependencies]
event_driver = { path = "./event_driver" }
small_derive_deref = "0.1.3"
ordered-float = "4.6.0"
hecs = "0.10.5"
log = "0.4.25"
