[package]
name = "prometheus"
version = "0.1.0"
edition = "2021"

[dependencies]
event_driver = { path = "./event_driver" }
small_derive_deref = "0.1.3"
small_read_only = "0.1.0"
ordered-float = "4.6.0" # NN
hecs = "0.10.5"
log = "0.4.25"
winit = "0.30.8"
env_logger = "0.11.6"